const docEl=document.documentElement;
const body=document.body;
const themeButton=document.querySelector('.theme-toggle');
const navToggle=document.querySelector('.nav-toggle');
const nav=document.querySelector('.site-nav');
const navLinks=[...document.querySelectorAll('.nav-link')];
const sections=[...document.querySelectorAll('section[data-section]')];
const scrollLinks=[...document.querySelectorAll('[data-scroll]')];
const projectsGrid=document.getElementById('projects-grid');
const projectTemplate=document.getElementById('project-card-template');
const yearTarget=document.querySelector('[data-year]');
const avatarImg=document.querySelector('.avatar img');
const revealGroups=[...document.querySelectorAll('[data-reveal-group]')];
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const systemTheme=window.matchMedia('(prefers-color-scheme: dark)');
const THEME_KEY='theme-preference';
const themeCycle=['light','dark','system'];
let refreshGradientTiles=()=>{};
const anchorTimers=new WeakMap();
const getStoredTheme=()=>{try{return localStorage.getItem(THEME_KEY)||'system';}catch(error){return'system';}};
const resolveTheme=(mode)=>mode==='system'?(systemTheme.matches?'dark':'light'):mode;
const applyTheme=(mode)=>{const resolved=resolveTheme(mode);docEl.dataset.theme=resolved;refreshGradientTiles();if(!themeButton)return;themeButton.dataset.mode=mode;const nextMode=themeCycle[(themeCycle.indexOf(mode)+1)%themeCycle.length];themeButton.setAttribute('aria-label',`Activate ${nextMode} theme`);themeButton.setAttribute('title',`Switch to ${nextMode} theme`);};
if(themeButton){applyTheme(getStoredTheme());const handleSystemChange=()=>{if((themeButton.dataset.mode||'system')==='system')applyTheme('system');};if(systemTheme.addEventListener){systemTheme.addEventListener('change',handleSystemChange);}else if(systemTheme.addListener){systemTheme.addListener(handleSystemChange);}themeButton.addEventListener('click',()=>{const current=themeButton.dataset.mode||getStoredTheme();const next=themeCycle[(themeCycle.indexOf(current)+1)%themeCycle.length];try{localStorage.setItem(THEME_KEY,next);}catch(error){}applyTheme(next);});}
if(yearTarget)yearTarget.textContent=new Date().getFullYear();
window.requestAnimationFrame(()=>body.classList.add('is-ready'));
if(navToggle&&nav){navToggle.addEventListener('click',()=>{const expanded=navToggle.getAttribute('aria-expanded')==='true';navToggle.setAttribute('aria-expanded',String(!expanded));nav.classList.toggle('open',!expanded);});}
const closeMobileNav=()=>{if(!navToggle||!nav)return;navToggle.setAttribute('aria-expanded','false');nav.classList.remove('open');};
const focusSection=(target)=>{if(typeof target.focus!=='function')return;window.requestAnimationFrame(()=>{try{target.focus({preventScroll:true});}catch(error){target.focus();}});};
const highlightSection=(target)=>{if(!target)return;target.classList.add('is-anchor-target');const timer=anchorTimers.get(target);if(timer)window.clearTimeout(timer);anchorTimers.set(target,window.setTimeout(()=>{target.classList.remove('is-anchor-target');anchorTimers.delete(target);},900));};
const handleAnchorScroll=(event,target)=>{if(!target)return;event.preventDefault();target.scrollIntoView({behavior:reduceMotion?'auto':'smooth',block:'start'});focusSection(target);const delay=reduceMotion?0:520;window.setTimeout(()=>highlightSection(target),delay);if(typeof history.pushState==='function'){history.pushState(null,'',`#${target.id}`);}else{window.location.hash=`#${target.id}`;}};
scrollLinks.forEach((link)=>{const href=link.getAttribute('href')||'';if(!href.startsWith('#'))return;const target=document.querySelector(href);if(!target)return;link.addEventListener('click',(event)=>{if(link.classList.contains('nav-link'))closeMobileNav();handleAnchorScroll(event,target);});});
if(avatarImg){avatarImg.addEventListener('error',()=>{const wrapper=avatarImg.closest('.avatar');if(!wrapper||wrapper.classList.contains('is-fallback'))return;wrapper.classList.add('is-fallback');const fallback=document.createElement('span');fallback.className='avatar-fallback';fallback.textContent=wrapper.dataset.initials||'AM';fallback.setAttribute('aria-hidden','true');wrapper.append(fallback);wrapper.setAttribute('role','img');wrapper.setAttribute('aria-label','Initials for Ammaar Murshid');});}
revealGroups.forEach((group)=>{const items=[...group.querySelectorAll('[data-reveal-item]')];items.forEach((item,index)=>{const delay=Math.min(index,6)*70;item.style.setProperty('--delay',`${delay}ms`);});});
const revealElements=()=>{const revealTargets=[...document.querySelectorAll('[data-reveal]')];if(!revealTargets.length)return;if(reduceMotion||!('IntersectionObserver'in window)){revealTargets.forEach((el)=>el.classList.add('is-visible'));revealGroups.forEach((group)=>group.classList.add('is-visible'));return;}const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(!entry.isIntersecting)return;entry.target.classList.add('is-visible');observer.unobserve(entry.target);});},{threshold:0.2});revealTargets.forEach((el)=>observer.observe(el));revealGroups.forEach((group)=>observer.observe(group));};
revealElements();
const fallbackProjects=[{name:'azure-labs-toolkit',description:'Infrastructure blueprints and scripts for Azure learning environments.',html_url:'https://github.com/ammaarM/azure-labs-toolkit',homepage:'',stargazers_count:12,topics:['azure','terraform','iac'],updated_at:'2024-01-12T00:00:00Z',full_name:'ammaarM/azure-labs-toolkit'},{name:'k8s-deployment-templates',description:'Opinionated Kubernetes deployment templates for rapid app delivery.',html_url:'https://github.com/ammaarM/k8s-deployment-templates',homepage:'',stargazers_count:8,topics:['kubernetes','helm','devops'],updated_at:'2023-11-02T00:00:00Z',full_name:'ammaarM/k8s-deployment-templates'},{name:'platform-observability-kit',description:'Dashboards and alerts that surface platform health signals.',html_url:'https://github.com/ammaarM/platform-observability-kit',homepage:'',stargazers_count:5,topics:['observability','dashboards'],updated_at:'2023-09-18T00:00:00Z',full_name:'ammaarM/platform-observability-kit'}];
const projectSorter=(a,b)=>b.stargazers_count!==a.stargazers_count?b.stargazers_count-a.stargazers_count:new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime();
const initialsFor=(name='Project')=>name.split(/[-_\s]+/).filter(Boolean).map((chunk)=>chunk.charAt(0).toUpperCase()).slice(0,3).join('')||'PR';
const gradientDataUri=(name)=>{const initials=initialsFor(name);const dark=docEl.dataset.theme==='dark';const start=dark?'#1f355a':'#2f6df6';const end=dark?'#3b6edc':'#68a0ff';const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1280 720" role="img" aria-labelledby="title"><defs><linearGradient id="g" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="${start}"/><stop offset="100%" stop-color="${end}"/></linearGradient></defs><rect width="1280" height="720" rx="56" fill="url(#g)"/><text id="title" x="50%" y="52%" text-anchor="middle" font-family="'Inter','Segoe UI',sans-serif" font-size="260" fill="rgba(255,255,255,0.9)" letter-spacing="18">${initials}</text></svg>`;return`data:image/svg+xml,${encodeURIComponent(svg)}`;};
refreshGradientTiles=()=>{document.querySelectorAll('img[data-gradient="true"]').forEach((img)=>{const name=img.dataset.gradientName||'Project';img.src=gradientDataUri(name);});};
const setFallbackContent=(media,type,project)=>{const img=media.querySelector('.project-preview');const fallback=media.querySelector('.project-fallback');const shimmer=media.querySelector('.project-shimmer');if(img){img.removeAttribute('src');img.hidden=true;}if(fallback){fallback.hidden=false;fallback.replaceChildren();if(type==='homepage'&&project.homepage){const link=document.createElement('a');link.className='project-home-link';link.href=project.homepage;link.target='_blank';link.rel='noreferrer';link.textContent='Visit live site';fallback.append(link);}else{const dataUri=gradientDataUri(project.name);const tile=document.createElement('img');tile.src=dataUri;tile.alt=`Stylized initials for ${project.name}`;tile.loading='lazy';tile.decoding='async';tile.width=1280;tile.height=720;tile.dataset.gradient='true';tile.dataset.gradientName=project.name||'Project';fallback.append(tile);}}media.classList.add('ready');if(shimmer)shimmer.style.opacity='0';};
const applyProjectPreview=(media,project)=>{if(!media)return;const img=media.querySelector('.project-preview');if(!img)return;const previewUrl=project.open_graph_image_url||(project.full_name?`https://opengraph.githubassets.com/1/${project.full_name}`:'');img.alt=`Preview of ${project.name}`;if(previewUrl){img.hidden=false;img.src=previewUrl;const markReady=()=>media.classList.add('ready');img.addEventListener('load',markReady,{once:true});img.addEventListener('error',()=>{if(project.homepage){setFallbackContent(media,'homepage',project);}else{setFallbackContent(media,'gradient',project);}},{once:true});if(img.complete&&img.naturalWidth)markReady();}else if(project.homepage){setFallbackContent(media,'homepage',project);}else{setFallbackContent(media,'gradient',project);}};
const renderProjects=(projects)=>{if(!projectsGrid||!projectTemplate)return;projectsGrid.innerHTML='';if(!projects.length){const empty=document.createElement('p');empty.textContent='No projects to show right now. Check back soon!';projectsGrid.append(empty);return;}projects.forEach((project,index)=>{const card=projectTemplate.content.firstElementChild.cloneNode(true);card.style.setProperty('--delay',`${Math.min(index,8)*60}ms`);const media=card.querySelector('.project-media');const title=card.querySelector('.project-title');const stars=card.querySelector('.project-stars');const description=card.querySelector('.project-description');const tags=card.querySelector('.project-tags');const repoLink=card.querySelector('.project-repo');const demoLink=card.querySelector('.project-demo');if(title)title.textContent=project.name;if(stars){stars.textContent=`⭐ ${project.stargazers_count}`;stars.setAttribute('aria-label',`${project.stargazers_count} GitHub stars`);}if(description)description.textContent=project.description||'A recent project by Ammaar Murshid.';if(tags){tags.innerHTML='';(project.topics||[]).slice(0,6).forEach((topic)=>{const tag=document.createElement('span');tag.textContent=topic;tags.append(tag);});if(!tags.children.length)tags.remove();}if(repoLink){repoLink.href=project.html_url;repoLink.setAttribute('aria-label',`${project.name} repository`);}if(demoLink){if(project.homepage){demoLink.href=project.homepage;demoLink.hidden=false;}else{demoLink.hidden=true;}}applyProjectPreview(media,project);projectsGrid.append(card);});};
const loadProjects=async()=>{if(!projectsGrid||!projectTemplate)return;const loading=document.createElement('p');loading.textContent='Loading projects…';loading.className='project-loading';projectsGrid.append(loading);try{const response=await fetch('https://api.github.com/users/ammaarM/repos?per_page=100',{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)throw new Error('Network response not ok');const data=await response.json();const filtered=data.filter((repo)=>!repo.fork&&!repo.archived).sort(projectSorter).slice(0,12);renderProjects(filtered.length?filtered:fallbackProjects);}catch(error){console.error('GitHub projects failed to load',error);renderProjects(fallbackProjects);}};
loadProjects();
const updateActiveNav=(sectionId)=>{navLinks.forEach((link)=>{const targetId=(link.getAttribute('href')||'').replace('#','');const isActive=targetId===sectionId;link.classList.toggle('is-active',isActive);if(isActive){link.setAttribute('aria-current','page');}else{link.removeAttribute('aria-current');}});};
if(sections.length&&navLinks.length){if(!reduceMotion&&'IntersectionObserver'in window){const observer=new IntersectionObserver((entries)=>{entries.forEach((entry)=>{if(entry.isIntersecting)updateActiveNav(entry.target.id);});},{threshold:0.45,rootMargin:'-35% 0px -45% 0px'});sections.forEach((section)=>observer.observe(section));}else{const handleScroll=()=>{const scrollY=window.scrollY+window.innerHeight*0.35;let currentId=sections[0].id;sections.forEach((section)=>{if(scrollY>=section.offsetTop)currentId=section.id;});updateActiveNav(currentId);};handleScroll();window.addEventListener('scroll',handleScroll,{passive:true});}}
